# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: voice_bucket.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='voice_bucket.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12voice_bucket.proto\x12\x05proto\"\x06\n\x04Void\"4\n\x1a\x43onvertVideoToAudioRequest\x12\x16\n\x0eSourceVideoURL\x18\x01 \x01(\t2\x8a\x01\n\x14\x41udioDownloadService\x12G\n\x13\x43onvertVideoToAudio\x12!.proto.ConvertVideoToAudioRequest\x1a\x0b.proto.Void\"\x00\x12)\n\x0bHealthCheck\x12\x0b.proto.Void\x1a\x0b.proto.Void\"\x00\x62\x06proto3'
)




_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='proto.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=35,
)


_CONVERTVIDEOTOAUDIOREQUEST = _descriptor.Descriptor(
  name='ConvertVideoToAudioRequest',
  full_name='proto.ConvertVideoToAudioRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='SourceVideoURL', full_name='proto.ConvertVideoToAudioRequest.SourceVideoURL', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['ConvertVideoToAudioRequest'] = _CONVERTVIDEOTOAUDIOREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'voice_bucket_pb2'
  # @@protoc_insertion_point(class_scope:proto.Void)
  })
_sym_db.RegisterMessage(Void)

ConvertVideoToAudioRequest = _reflection.GeneratedProtocolMessageType('ConvertVideoToAudioRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONVERTVIDEOTOAUDIOREQUEST,
  '__module__' : 'voice_bucket_pb2'
  # @@protoc_insertion_point(class_scope:proto.ConvertVideoToAudioRequest)
  })
_sym_db.RegisterMessage(ConvertVideoToAudioRequest)



_AUDIODOWNLOADSERVICE = _descriptor.ServiceDescriptor(
  name='AudioDownloadService',
  full_name='proto.AudioDownloadService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=92,
  serialized_end=230,
  methods=[
  _descriptor.MethodDescriptor(
    name='ConvertVideoToAudio',
    full_name='proto.AudioDownloadService.ConvertVideoToAudio',
    index=0,
    containing_service=None,
    input_type=_CONVERTVIDEOTOAUDIOREQUEST,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='HealthCheck',
    full_name='proto.AudioDownloadService.HealthCheck',
    index=1,
    containing_service=None,
    input_type=_VOID,
    output_type=_VOID,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUDIODOWNLOADSERVICE)

DESCRIPTOR.services_by_name['AudioDownloadService'] = _AUDIODOWNLOADSERVICE

# @@protoc_insertion_point(module_scope)
