# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import voice_bucket_pb2 as voice__bucket__pb2


class AudioDownloadServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ConvertVideoToAudio = channel.unary_unary(
        '/proto.AudioDownloadService/ConvertVideoToAudio',
        request_serializer=voice__bucket__pb2.ConvertVideoToAudioRequest.SerializeToString,
        response_deserializer=voice__bucket__pb2.Void.FromString,
        )
    self.HealthCheck = channel.unary_unary(
        '/proto.AudioDownloadService/HealthCheck',
        request_serializer=voice__bucket__pb2.Void.SerializeToString,
        response_deserializer=voice__bucket__pb2.Void.FromString,
        )


class AudioDownloadServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ConvertVideoToAudio(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HealthCheck(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AudioDownloadServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ConvertVideoToAudio': grpc.unary_unary_rpc_method_handler(
          servicer.ConvertVideoToAudio,
          request_deserializer=voice__bucket__pb2.ConvertVideoToAudioRequest.FromString,
          response_serializer=voice__bucket__pb2.Void.SerializeToString,
      ),
      'HealthCheck': grpc.unary_unary_rpc_method_handler(
          servicer.HealthCheck,
          request_deserializer=voice__bucket__pb2.Void.FromString,
          response_serializer=voice__bucket__pb2.Void.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'proto.AudioDownloadService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
